### PR TITLE
Add Russian localisation for Hitokori and Solosu

### PR DESCRIPTION
**Pull request by Loreos7**

### CODE REVIEW

**Comment by Flutterish** [comment]
I've add some missing keys you requested, please translate them too

**Comment by Flutterish** [comment]
Also, should mod names not be translated? If you think so, I probably should make a note of this in the readme

**Comment by Loreos7** [comment]
image
image
Could you also fix a typo?

**Comment by Flutterish** [comment]
looks good to me, I'll remove the mod titles on the main branch

**Pull request merged**
